[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00d2ff"
backgroundColor = "#05051a"
secondaryBackgroundColor = "#0a0a2e"
textColor = "#ccd6f6"
font = "sans serif"
